// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: serviceStatus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TowerOfDaedalus_WebApp_Kafka.Protobuf {

  /// <summary>Holder for reflection information generated from serviceStatus.proto</summary>
  public static partial class ServiceStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for serviceStatus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzZXJ2aWNlU3RhdHVzLnByb3RvEiVUb3dlck9mRGFlZGFsdXNfV2ViQXBw",
            "X0thZmthLlByb3RvYnVmItQBCg1TZXJ2aWNlU3RhdHVzEg4KBnN0YXR1cxgB",
            "IAEoCRJNCgR0eXBlGAIgASgOMj8uVG93ZXJPZkRhZWRhbHVzX1dlYkFwcF9L",
            "YWZrYS5Qcm90b2J1Zi5TZXJ2aWNlU3RhdHVzLlN0YXR1c1R5cGUSEAoIY2Fw",
            "YWNpdHkYAyABKAUiUgoKU3RhdHVzVHlwZRIMCghTSFVURE9XThAAEgwKCFNU",
            "QVJUSU5HEAESCwoHSEVBTFRIWRACEg0KCVVOSEVBTFRIWRADEgwKCFNUT1BQ",
            "SU5HEARCKKoCJVRvd2VyT2ZEYWVkYWx1c19XZWJBcHBfS2Fma2EuUHJvdG9i",
            "dWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus), global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Parser, new[]{ "Status", "Type", "Capacity" }, null, new[]{ typeof(global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ServiceStatus : pb::IMessage<ServiceStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServiceStatus> _parser = new pb::MessageParser<ServiceStatus>(() => new ServiceStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServiceStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceStatus(ServiceStatus other) : this() {
      status_ = other.status_;
      type_ = other.type_;
      capacity_ = other.capacity_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceStatus Clone() {
      return new ServiceStatus(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType type_ = global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType.Shutdown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "capacity" field.</summary>
    public const int CapacityFieldNumber = 3;
    private int capacity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Capacity {
      get { return capacity_; }
      set {
        capacity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServiceStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServiceStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (Type != other.Type) return false;
      if (Capacity != other.Capacity) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (Type != global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType.Shutdown) hash ^= Type.GetHashCode();
      if (Capacity != 0) hash ^= Capacity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Status);
      }
      if (Type != global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType.Shutdown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Capacity != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Capacity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Status);
      }
      if (Type != global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType.Shutdown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Capacity != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Capacity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (Type != global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType.Shutdown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Capacity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Capacity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServiceStatus other) {
      if (other == null) {
        return;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      if (other.Type != global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType.Shutdown) {
        Type = other.Type;
      }
      if (other.Capacity != 0) {
        Capacity = other.Capacity;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Status = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType) input.ReadEnum();
            break;
          }
          case 24: {
            Capacity = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Status = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::TowerOfDaedalus_WebApp_Kafka.Protobuf.ServiceStatus.Types.StatusType) input.ReadEnum();
            break;
          }
          case 24: {
            Capacity = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ServiceStatus message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum StatusType {
        [pbr::OriginalName("SHUTDOWN")] Shutdown = 0,
        [pbr::OriginalName("STARTING")] Starting = 1,
        [pbr::OriginalName("HEALTHY")] Healthy = 2,
        [pbr::OriginalName("UNHEALTHY")] Unhealthy = 3,
        [pbr::OriginalName("STOPPING")] Stopping = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
